version: "2"
services:
  server:
    container_name: node-starter
    restart: always
    build: ./
    volumes:
      - ./:/var/node-starter
      - ./node_modules:/var/node-starter/node_modules
    ports:
      - "7010:7010"
    links:
      - mongodb
      - redisdb
    environment:
      - NODE_ENV=development
    networks:
      - nodstnetwork
  mongodb:
    container_name: node-starter-mongo
    image: mongo
    volumes:
      - /Users/zegeek/Desktop/CODING/Docker/volumes/node-starter/mongo:/data/db
    ports:
      - "27000:27017"
    networks:
      - nodstnetwork
  redisdb:
    container_name: node-starter-redis
    image: redis
    volumes:
      - /Users/zegeek/Desktop/CODING/Docker/volumes/node-starter/redis:/data/db
    ports:
      - "6479:6379"
    networks:
      - nodstnetwork
networks:
  nodstnetwork:
    driver: bridge
