version: "2"
services:
  server:
    container_name: node-starter
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/node-starter
      - ./node_modules:/var/node-starter/node_modules
    env_file: .env
    ports:
      - "7010:7010"
    links:
      - mongodb
      - redisdb
    depends_on:
      - mongodb
      - redisdb
    environment:
      WAIT_HOSTS: redisdb:6379, mongodb:27017
    networks:
      - nodstnetwork
  mongodb:
    container_name: node-starter-mongo
    image: mongo
    volumes:
      - ~/Desktop/CODING/Docker/volumes/node-starter/mongo:/data/db
    ports:
      - "27000:27017"
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
      - MONGO_INITDB_DATABASE=$DB_NAME
    networks:
      - nodstnetwork
  redisdb:
    container_name: node-starter-redis
    image: redis
    volumes:
      - ~/Desktop/CODING/Docker/volumes/node-starter/redis:/data/db
    ports:
      - "6479:6379"
    networks:
      - nodstnetwork
networks:
  nodstnetwork:
    driver: bridge
volumes:
  postgres:
